name: Exec Action Litigtion Update
on:
  # for manual invocation
  workflow_dispatch:
  schedule:
    - cron: '1 */4 * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: run
        name: Run
        uses: ./.github/actions/eo_scraper
 
