name: Exec Action Litigtion Update
on:
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Scheduled too
  schedule:
    - cron: '1 */4 * * *'

jobs:
  scrape:
    name: Scrape
    defaults:
      run:
        shell: bash
        working-directory: ./exec_order_lawsuits
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: run
        name: Run
        uses: ./.github/actions/eo_scraper
 
